name: Deploy Images to GHCR

on:
  push:
    branches:
      - main

jobs:
  push-store-image:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN_FOR_GHCR }}

      - name: 'Build Image Develop'
        run: |
          echo ${{ secrets.BOT_ENV }} | base64 -d > .env &&
          make build-prod && make push-prod

      # - name: 'Deploy Image on render'
      #   run: |
      #     curl ${{ secrets.DEV_RENDER_URL }}
